name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 1.9
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
      #env:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
